# Generated by Django 3.2.4 on 2021-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='evening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('prompt_1', models.TextField(max_length=200)),
                ('prompt_2', models.TextField(max_length=200)),
                ('prompt_3', models.TextField(max_length=200)),
            ],
        ),
    ]
